PROJECT = erlang
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy mysql
dep_cowboy_commit = master
dep_mysql = git https://github.com/mysql-otp/mysql-otp 1.6.0

include erlang.mk
